package me.belucky.toolscenter.model.table;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("T_ETC_INFO", "ID", TEtcInfo.class);
		arp.addMapping("T_ETC_INFO_1", "ID", TEtcInfo1.class);
		arp.addMapping("T_ETC_INFO_2", "ID", TEtcInfo2.class);
	}
}

