package me.belucky.toolscenter.model.table;

import me.belucky.toolscenter.model.table.base.BaseTEtcInfo2;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TEtcInfo2 extends BaseTEtcInfo2<TEtcInfo2> {
	public static final TEtcInfo2 dao = new TEtcInfo2().dao();
}
