package me.belucky.toolscenter.model.table;

import me.belucky.toolscenter.model.table.base.BaseTEtcInfo1;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TEtcInfo1 extends BaseTEtcInfo1<TEtcInfo1> {
	public static final TEtcInfo1 dao = new TEtcInfo1().dao();
}
