package me.belucky.toolscenter.model.table;

import me.belucky.toolscenter.model.table.base.BaseTEtcInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TEtcInfo extends BaseTEtcInfo<TEtcInfo> {
	public static final TEtcInfo dao = new TEtcInfo().dao();
}
