package me.belucky.toolscenter.model.table.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTEtcInfo2<M extends BaseTEtcInfo2<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public void setCPH(java.lang.String CPH) {
		set("CPH", CPH);
	}
	
	public java.lang.String getCPH() {
		return getStr("CPH");
	}

	public void setIDNO(java.lang.String IDNO) {
		set("IDNO", IDNO);
	}
	
	public java.lang.String getIDNO() {
		return getStr("IDNO");
	}

	public void setJsonStr(java.lang.String jsonStr) {
		set("JSON_STR", jsonStr);
	}
	
	public java.lang.String getJsonStr() {
		return getStr("JSON_STR");
	}

	public void setIsSign(java.lang.String isSign) {
		set("IS_SIGN", isSign);
	}
	
	public java.lang.String getIsSign() {
		return getStr("IS_SIGN");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("CREATE_TIME", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("CREATE_TIME");
	}

}
