package me.belucky.toolscenter.model.table.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTEtcInfo<M extends BaseTEtcInfo<M>> extends Model<M> implements IBean {

	public void setID(java.lang.Integer ID) {
		set("ID", ID);
	}
	
	public java.lang.Integer getID() {
		return getInt("ID");
	}

	public void setCPH(java.lang.String CPH) {
		set("CPH", CPH);
	}
	
	public java.lang.String getCPH() {
		return getStr("CPH");
	}

}
